name: Build Plugin

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    env:
      EXILED_REFERENCES: ${{ github.workspace }}\References

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Checkout References
      uses: actions/checkout@v4
      with:
        repository: MS-crew/SL-References
        path: References
        token: ${{ secrets.REFERANCES_REPO_KEY }}

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore NuGet Packages
      run: dotnet restore

    - name: Build Plugin
      run: dotnet build --configuration Release --no-restore

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: NightVisionGoggles-DLL
        path: '**/bin/Release/**/NightVisionGoggles.dll'
