name: Build Plugin

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

env:
  EXILED_REFERENCES: ${{ github.workspace }}\References

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Checkout Private References
      uses: actions/checkout@v4
      with:
        repository: MS-crew/SL-References
        token: ${{ secrets.REFERANCES_REPO_KEY }}
        path: Temp_Repo 

    - name: Extract References
      shell: pwsh
      run: |
        # Hedef klasörü oluştur (References)
        New-Item -ItemType Directory -Force -Path "${{ env.EXILED_REFERENCES }}"

        # Temp_Repo klasörüne inen References.zip dosyasını alıp hedef yere açıyoruz
        Expand-Archive -Path "Temp_Repo\References.zip" -DestinationPath "${{ env.EXILED_REFERENCES }}" -Force
        
        # KONTROL (Hata olursa görelim diye):
        Write-Host "--- AÇILAN DOSYALAR ---"
        Get-ChildItem -Path "${{ env.EXILED_REFERENCES }}" -Recurse

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore NuGet Packages
      run: dotnet restore

    - name: Build Plugin
      run: dotnet build --configuration Release --no-restore

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: NightVisionGoggles-DLL
        path: '**/bin/Release/**/NightVisionGoggles.dll'
