name: Build Plugin

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Checkout Private References
      uses: actions/checkout@v4
      with:
        repository: MS-crew/SL-References
        token: ${{ secrets.REFERANCES_REPO_KEY }}
        path: RepoDownload 

    - name: Force Extract References
      shell: pwsh
      run: |
        New-Item -ItemType Directory -Force -Path "References"
        New-Item -ItemType Directory -Force -Path "Temp_Unzip"
        Expand-Archive -Path "RepoDownload\References.zip" -DestinationPath "Temp_Unzip" -Force
        
        # DLL'leri ana klasöre taşı
        Get-ChildItem -Path "Temp_Unzip" -Recurse -Filter "*.dll" | ForEach-Object {
            Move-Item -Path $_.FullName -Destination "References" -Force
        }

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2

    - name: Restore NuGet Packages
      run: nuget restore NightVisionGoggles.sln

    - name: Build with MSBuild
      run: msbuild NightVisionGoggles.csproj /p:Configuration=Release /p:EXILED_REFERENCES="${{ github.workspace }}\References"

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: NightVisionGoggles-DLL
        path: '**/bin/Release/**/NightVisionGoggles.dll'
